### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by flean** [krstffr/meteor-fb-feed-getter#3]
I'm getting this bug

```
Exception in setInterval callback: Error: failed [503] <!DOCTYPE html> <html lang="en" id="facebook">   <head>     <title>Facebook | Error</title>     <meta charset="utf-8">     <meta http-equiv="cache-control" content="no-cache">     <meta http-equiv="cache-control" content="no-store">     <meta http-equiv="cache-control" content="max-age=0">     <meta http-equiv="expires" content="-1">     <meta http-equiv="pragma" content="no-cache">     <meta name="robots" content="noindex,nofollow">     <style>       html, body {         color: #141823;        ...
    at Object.Future.wait (/mnt/app/programs/server/node_modules/fibers/future.js:398:15)
    at Object.<anonymous> (packages/meteor/helpers.js:119:1)
    at Object.HTTP.call (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:3070:1)
    at [object Object].that.getFeed (packages/krstffr_fb-feed-getter/packages/krstffr_fb-feed-getter.js:93:1)
    at [object Object].that.scheduleFallback (packages/krstffr_fb-feed-getter/packages/krstffr_fb-feed-getter.js:131:1)
    at packages/krstffr_fb-feed-getter/packages/krstffr_fb-feed-getter.js:198:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
    - - - - -
    at makeErrorByStatus (packages/http/httpcall_common.js:16:1)
    at Request._callback (packages/http/httpcall_server.js:113:1)
    at Request.self.callback (/mnt/app/programs/server/npm/http/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/mnt/app/programs/server/npm/http/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/mnt/app/programs/server/npm/http/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
Exception in setInterval callback: Error: connect ETIMEDOUT
    at Object.Future.wait (/mnt/app/programs/server/node_modules/fibers/future.js:398:15)
    at Object.<anonymous> (packages/meteor/helpers.js:119:1)
    at Object.HTTP.call (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:3070:1)
    at [object Object].that.getFeed (packages/krstffr_fb-feed-getter/packages/krstffr_fb-feed-getter.js:93:1)
    at [object Object].that.scheduleFallback (packages/krstffr_fb-feed-getter/packages/krstffr_fb-feed-getter.js:131:1)
    at packages/krstffr_fb-feed-getter/packages/krstffr_fb-feed-getter.js:198:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
    - - - - -
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```

**Comment by krstffr** [comment]
It appears the connection to facebook timedout, probably due to your network connection. @flean 

See this:

```Error: connect ETIMEDOUT```

That's all I can see from provided information.
